"""empty message

Revision ID: 569132badae2
Revises: 9f6ca44a3646
Create Date: 2025-02-21 12:30:15.081349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569132badae2'
down_revision = '9f6ca44a3646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pressure', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('pressure')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
